# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38025dca32d202fe15cdcc75a5b027167617f1edf360a58353eaab189a6e02d600afc9fd15428a363e47f13113a53308c23aec62b7424fe91696bd6fa29dead

test:
  secret_key_base: 8c01e4246ec9e5883a6e203c0ccee8d9ff04fb35f1d918220df39793e5b9053443fdf5630dd62a464ccf3ba0535032b2476468ad74437549006a91494af20aa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
